In [1]:
import mysql.connector

In [2]:
from __future__ import print_function

localhost = "localhost"

yourusername = "root"

yourpassword = "Manan*2005"

yourdbname = "colge"

connection = mysql.connector.connect( host=localhost, user=yourusername, passwd=yourpassword, db=yourdbname )


cursor = connection.cursor()

In [3]:
def add_students(student_id, first_name, last_name, branch, gender,cpi, DOB, phone, email, fathers_phone, fathers_email, course1, course2, course3):
    query = "INSERT INTO Students VALUES (%s, %s, %s, %s, %s ,%s)"
    cursor.execute(query, (student_id, first_name, last_name, branch, gender,cpi))
    query = "INSERT INTO Student_info VALUES (%s, %s, %s, %s, %s, %s)"
    cursor.execute(query, (student_id,  DOB, phone, email, fathers_phone, fathers_email))
    query = "INSERT INTO Student_courses VALUES (%s, %s, %s, %s)"
    cursor.execute(query, (student_id, course1, course2, course3))
    connection.commit()

In [4]:
while(1):
    x=int(input("1.Add Students: \n2.Exit: \n"))
    if(x==1):
        student_id = (input("Student ID: "))
        first_name = (input("First Name: "))
        last_name = (input("Last Name: "))
        branch = (input("Branch: "))
        gender = (input("Gender: "))
        cpi = (input("CPI: "))
        DOB = (input("DOB: "))
        phone = (input("Phone No.: "))
        email = (input("Email ID: "))
        fathers_phone = (input("Father's Phone: "))
        fathers_email = (input("Father's Email ID: "))
        course1 =(input("Course No. 1: "))
        course2 =(input("Course No. 2: "))
        course3 =(input("Course No. 3: ")) 
        add_students(student_id, first_name, last_name, branch, gender,cpi, DOB, phone, email, fathers_phone, fathers_email, course1, course2, course3)
    else:
        break

1.Add Students:
2.Exit:
 2

In [7]:
def add_profs(prof_id, first_name, last_name, department, gender, phone, email, office_no):
    query = "INSERT INTO Professors VALUES (%s, %s, %s, %s, %s, %s, %s, %s)"
    cursor.execute(query, (prof_id, first_name, last_name, department, gender, phone, email, office_no))
    connection.commit()

In [ ]:
while(1):
    x=int(input("1.Add Profs: \n2.Exit: \n"))
    if(x==1):
        prof_id = (input("Professor ID: "))
        first_name = (input("First Name: "))
        last_name = (input("Last Name: "))
        department = (input("Department: "))
        gender =(input("Gender: "))
        phone = (input("Phone No.: "))
        email = (input("Email ID: "))
        office_no = (input("Office Number: "))
        add_profs(prof_id, first_name, last_name, department, gender, phone, email, office_no)
    else:
        break

1.Add Profs:
2.Exit:
 1
Professor ID:  103
First Name:  Ajit
Last Name:  Ganguly
Department:  MTH
Gender:  M
Phone No.:  7847854781
Email ID:  ajgan@iitk.ac.in
Office Number:  7845
1.Add Profs:
2.Exit:
 1
Professor ID:  104
First Name:  Somesh
Last Name:  Jha
Department:  MTH
Gender:  M
Phone No.:  7899956785
Email ID:  sjha@iitk.ac.in
Office Number:  7985
1.Add Profs:
2.Exit:
 1
Professor ID:  110
First Name:  Zakir
Last Name:  Khan
Department:  PHY
Gender:  M
Phone No.:  7445695234
Email ID:  zkhan@iitk.ac.in
Office Number:  8774
1.Add Profs:
2.Exit:
 1
Professor ID:  106
First Name:  Minirwa
Last Name:  Chatterjee
Department:  CE
Gender:  F
Phone No.:  8544985627
Email ID:  minic@iitk.ac.in
Office Number:  9987
1.Add Profs:
2.Exit:
 1
Professor ID:  107
First Name:  Anil
Last Name:  Gada
Department:  CSE
Gender:  M
Phone No.:  9192748546
Email ID:  agada@iitk.ac.in
Office Number:  8798
1.Add Profs:
2.Exit:
 1
Professor ID:  108
First Name:  Somnath
Last Name:  Biswas
Department:  CSE
Gender:  M
Phone No.:  6278459985
Email ID:  swas@iitk.ac.in
Office Number:  9974
1.Add Profs:
2.Exit:
 1
Professor ID:  112
First Name:  Dootika
Last Name:  Srivastava
Department:  MSE
Gender:  F
Phone No.:  7992262498
Email ID:  dvasta@iitk.ac.in
Office Number:  8698
1.Add Profs:
2.Exit:
 1
Professor ID:  101
First Name:  Manish
Last Name:  Harbola
Department:  PHY
Gender:  M
Phone No.:  8452118579
Email ID:  mbola@iitk.ac.in
Office Number:  5500
1.Add Profs:
2.Exit:
 1
Professor ID:  102
First Name:  Sujata
Last Name:  Singh
Department:  PHY
Gender:  F
Phone No.:  7745198652
Email ID:  ssing@iitk.ac.in
Office Number:  7766
1.Add Profs:
2.Exit:
 1
Professor ID:  105
First Name:  Avinash
Last Name:  Barnwal
Department:  CHM
Gender:  M
Phone No.:  6887449532
Email ID:  awal@iitk.ac.in
Office Number:  8523
1.Add Profs:
2.Exit:
 1
Professor ID:  109
First Name:  Amit
Last Name:  Shiva
Department:  CHM
Gender:  M
Phone No.:  9445876523
Email ID:  ashiv@iitk.ac.in
Office Number:  9636
1.Add Profs:
2.Exit:
 1
Professor ID:  111
First Name:  Rik
Last Name:  Ley
Department:  EE
Gender:  M
Phone No.:  7992298465
Email ID:  rley@iitk.ac.in
Office Number:  6973

In [29]:
connection.close()